import {useEffect,useRef,useState} from 'react';
export interface ChatFile {id:string;name:string;mime:string;size:number;state:string;error?:string;sent?:boolean;progress?:number;local?:boolean}
export function useChatAttachments(cid:string,authHeaders:()=>Record<string,string>){
  const [files,setFiles]=useState<ChatFile[]>([]),[error,setError]=useState('');const current=useRef(cid),uploads=useRef(new Map<string,XMLHttpRequest>()),removed=useRef(new Set<string>());current.current=cid;
  useEffect(()=>{setFiles([]);setError('');const controller=new AbortController();if(cid)void fetch(`/api/orbit/conversations/${encodeURIComponent(cid)}/attachments`,{headers:authHeaders(),signal:controller.signal}).then(async res=>{const data=await res.json();if(!res.ok)throw new Error(data.error);if(current.current===cid)setFiles(data.attachments.filter((f:ChatFile)=>!f.sent));}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{controller.abort();for(const req of uploads.current.values())req.abort();uploads.current.clear();};},[cid,authHeaders]);
  const upload=async(selected:File[])=>{if(files.length+selected.length>3||files.reduce((n,f)=>n+f.size,0)+selected.reduce((n,f)=>n+f.size,0)>20*1024*1024){setError('每轮最多 3 个附件，总计 20MB');return;}setError('');const owner=cid;
    for(const file of selected){if(file.size>10*1024*1024||!file.size){setError('单个附件必须在 1 字节到 10MB 之间');continue;}const mime=({jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',txt:'text/plain',md:'text/markdown',pdf:'application/pdf',csv:'text/csv',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'} as Record<string,string>)[file.name.split('.').at(-1)?.toLowerCase()||'']||file.type;const id=crypto.randomUUID();setFiles(old=>[...old,{id,name:file.name,mime,size:file.size,state:'uploading',progress:0,local:true}]);
      try{const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('读取文件失败'));reader.readAsDataURL(file);});if(current.current!==owner||removed.current.has(id))return;
        const result=await new Promise<ChatFile>((resolve,reject)=>{const req=new XMLHttpRequest();uploads.current.set(id,req);req.open('POST',`/api/orbit/conversations/${encodeURIComponent(owner)}/attachments`);req.setRequestHeader('Content-Type','application/json');for(const [key,value]of Object.entries(authHeaders()))req.setRequestHeader(key,value);req.upload.onprogress=e=>{if(e.lengthComputable&&current.current===owner)setFiles(old=>old.map(f=>f.id===id?{...f,progress:Math.round(e.loaded/e.total*100),state:e.loaded===e.total?'processing':'uploading'}:f));};req.onerror=()=>reject(new Error('上传失败，请重试'));req.onabort=()=>reject(new Error('上传已取消'));req.onload=()=>{try{const data=JSON.parse(req.responseText);req.status>=200&&req.status<300?resolve(data.attachment):reject(new Error(data.error||'附件上传失败'));}catch{reject(new Error('附件响应格式不正确'));}};req.timeout=60000;req.ontimeout=()=>reject(new Error('上传超时，请重试'));req.send(JSON.stringify({name:file.name,mime,base64}));});if(current.current===owner)setFiles(old=>old.map(f=>f.id===id?result:f));
      }catch(e){if(current.current===owner)setFiles(old=>old.map(f=>f.id===id?{...f,state:'local-failed',error:e instanceof Error?e.message:'上传失败'}:f));}finally{uploads.current.delete(id);}
    }
  };
  const remove=async(id:string)=>{setError('');const file=files.find(f=>f.id===id);if(file?.local){removed.current.add(id);uploads.current.get(id)?.abort();}else if(file?.state!=='local-failed'){try{const res=await fetch(`/api/orbit/attachments/${encodeURIComponent(id)}`,{method:'DELETE',headers:authHeaders()});if(!res.ok)throw new Error((await res.json()).error);}catch(e){setError(e instanceof Error?e.message:'移除失败');return;}}setFiles(old=>old.filter(f=>f.id!==id));};
  const retry=async(id:string)=>{const owner=cid;setFiles(old=>old.map(f=>f.id===id?{...f,state:'processing'}:f));try{const res=await fetch(`/api/orbit/attachments/${encodeURIComponent(id)}/retry`,{method:'POST',headers:authHeaders()});const data=await res.json();if(!res.ok)throw new Error(data.error);if(current.current===owner)setFiles(old=>old.map(f=>f.id===id?data.attachment:f));}catch(e){if(current.current===owner)setFiles(old=>old.map(f=>f.id===id?{...f,state:'failed',error:e instanceof Error?e.message:'解析失败'}:f));}};
  return {files,error,upload,remove,retry,clear:()=>setFiles([]),ready:files.every(f=>f.state==='ready')};
}
