import { queryAll, queryOne, run } from './database/connection.js';
import { getAttachment, getNotification } from './activity-store.js';
import { randomUUID,createHash } from 'node:crypto';
export function exportConnected(userId:string) {return {events:queryAll<any>('SELECT * FROM orbit_activity_events WHERE user_id=?',[userId]),reports:queryAll<any>('SELECT * FROM orbit_activity_reports WHERE user_id=?',[userId]),weekly:queryOne<any>('SELECT * FROM orbit_weekly_preferences WHERE user_id=?',[userId])||null,profile:queryOne<any>('SELECT * FROM orbit_profiles WHERE user_id=?',[userId])||null,notificationMessages:queryAll<any>('SELECT * FROM orbit_notification_messages WHERE user_id=?',[userId])};}
export function clearConnected(userId:string) {for(const table of ['orbit_activity_events','orbit_activity_reports','orbit_weekly_preferences','orbit_profiles','orbit_notification_messages'])run(`DELETE FROM ${table} WHERE user_id=?`,[userId]);}
export function restoreConnected(userId:string,data:Partial<ReturnType<typeof exportConnected>>|undefined,foreign:boolean,attachmentIds:Map<string,string>) {
  if(!data)return;
  const avatar=data.profile?.avatar_id?(attachmentIds.get(data.profile.avatar_id)||data.profile.avatar_id):null;
  if(avatar&&getAttachment(avatar,userId))run('INSERT INTO orbit_profiles (user_id,avatar_id) VALUES (?,?) ON CONFLICT(user_id) DO UPDATE SET avatar_id=excluded.avatar_id',[userId,avatar]);
  if(data.weekly){const w=data.weekly;if(!Number.isInteger(w.weekday)||w.weekday<0||w.weekday>6||!Number.isInteger(w.hour)||w.hour<0||w.hour>23||!Number.isInteger(w.minute)||w.minute<0||w.minute>59)throw new Error('周报备份设置无效');run('INSERT INTO orbit_weekly_preferences (user_id,enabled,weekday,hour,minute,last_cutoff) VALUES (?,0,?,?,?,NULL) ON CONFLICT(user_id) DO UPDATE SET enabled=0,weekday=excluded.weekday,hour=excluded.hour,minute=excluded.minute,last_cutoff=NULL',[userId,w.weekday,w.hour,w.minute]);}
  if(foreign){
    // Keep authorized historical evidence, but never follow the source account's IDs.
    for(const r of data.reports||[]){const parsed=JSON.parse(r.snapshot);if(!parsed.activity?.metricDetails||!parsed.window)throw new Error('报告快照无效');
      for(const rows of Object.values(parsed.activity.metricDetails) as any[][])for(const d of rows)d.href=null;
      for(const key of ['details','knowledgeDetails'])for(const d of parsed[key]||[])d.href=null;
      for(const d of parsed.activity.upcoming||[])d.href=null;
      const snapshot=JSON.stringify(parsed),hash=createHash('sha256').update(snapshot).digest('hex');
      run('INSERT OR IGNORE INTO orbit_activity_reports (id,user_id,range_start,range_end,snapshot,snapshot_hash,insights,created_at) VALUES (?,?,?,?,?,?,?,?)',[randomUUID(),userId,r.range_start,r.range_end,snapshot,hash,r.insights||null,r.created_at]);
    }
    for(const e of data.events||[]){if(!['task_created','task_rescheduled','ai_confirmed','note_optimized'].includes(e.kind)||!Number.isFinite(Date.parse(e.occurred_at)))throw new Error('活动事件备份无效');const metadata=JSON.parse(e.metadata);const id='restored:'+createHash('sha256').update(userId+':'+e.id).digest('hex');for(const k of ['created','updated','recurring'])if(Array.isArray(metadata[k]))metadata[k]=metadata[k].map((_:unknown,index:number)=>`unavailable:${id}:${k}:${index}`);metadata.referencesUnavailable=true;run('INSERT OR IGNORE INTO orbit_activity_events (id,user_id,kind,source_id,occurred_at,metadata) VALUES (?,?,?,?,?,?)',[id,userId,e.kind,`unavailable:${id}`,e.occurred_at,JSON.stringify(metadata)]);}
    return;
  }
  for(const e of data.events||[]){if(typeof e.id!=='string'||typeof e.source_id!=='string'||!['task_created','task_rescheduled','ai_confirmed','note_optimized'].includes(e.kind)||!Number.isFinite(Date.parse(e.occurred_at))||typeof e.metadata!=='string'||e.metadata.length>16000)throw new Error('活动事件备份无效');JSON.parse(e.metadata);const old=queryOne<any>('SELECT user_id FROM orbit_activity_events WHERE id=?',[e.id]);if(old&&old.user_id!==userId)throw new Error('活动事件编号属于其他账号');run('INSERT OR IGNORE INTO orbit_activity_events (id,user_id,kind,source_id,occurred_at,metadata) VALUES (?,?,?,?,?,?)',[e.id,userId,e.kind,e.source_id,e.occurred_at,e.metadata]);}
  for(const r of data.reports||[]){if(typeof r.id!=='string'||typeof r.snapshot!=='string'||r.snapshot.length>8*1024*1024||!Number.isFinite(Date.parse(r.range_start))||!Number.isFinite(Date.parse(r.range_end)))throw new Error('报告备份无效');const parsed=JSON.parse(r.snapshot);if(!parsed.activity?.metricDetails||!parsed.window)throw new Error('报告快照无效');const old=queryOne<any>('SELECT user_id FROM orbit_activity_reports WHERE id=?',[r.id]);if(old&&old.user_id!==userId)throw new Error('报告编号属于其他账号');run('INSERT OR IGNORE INTO orbit_activity_reports (id,user_id,range_start,range_end,snapshot,snapshot_hash,insights,insight_error,created_at,auto_cutoff) VALUES (?,?,?,?,?,?,?,?,?,NULL)',[r.id,userId,r.range_start,r.range_end,r.snapshot,r.snapshot_hash,r.insights||null,r.insight_error||null,r.created_at]);}
  for(const n of data.notificationMessages||[]){if(getNotification(n.notification_id,userId)&&typeof n.delivery_key==='string'&&queryOne('SELECT id FROM ai_schedule_messages WHERE id=? AND user_id=?',[n.message_id,userId]))run('INSERT OR IGNORE INTO orbit_notification_messages (notification_id,user_id,message_id,delivery_key) VALUES (?,?,?,?)',[n.notification_id,userId,n.message_id,n.delivery_key]);}
}
