import test from 'node:test';import assert from 'node:assert/strict';import ExcelJS from 'exceljs';
import {parseDocument} from './file-parser.js';import {validateOfficeArchive} from './archive-validation.mjs';
const docMime='application/vnd.openxmlformats-officedocument.wordprocessingml.document',sheetMime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
function zip(entries:Record<string,string>){let offset=0;const files:Buffer[]=[],directory:Buffer[]=[];for(const [name,text]of Object.entries(entries)){const data=Buffer.from(text),filename=Buffer.from(name);let crc=0xffffffff;for(const byte of data){crc^=byte;for(let i=0;i<8;i++)crc=crc>>>1^((crc&1)?0xedb88320:0);}crc=(crc^0xffffffff)>>>0;const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt32LE(crc,14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(data.length,22);local.writeUInt16LE(filename.length,26);files.push(local,filename,data);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(crc,16);central.writeUInt32LE(data.length,20);central.writeUInt32LE(data.length,24);central.writeUInt16LE(filename.length,28);central.writeUInt32LE(offset,42);directory.push(central,filename);offset+=local.length+filename.length+data.length;}const dir=Buffer.concat(directory),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(entries).length,8);end.writeUInt16LE(Object.keys(entries).length,10);end.writeUInt32LE(dir.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...files,dir,end]);}
const docEntries={'[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>','_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>','word/document.xml':'<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Orbit Office 内容</w:t></w:r></w:p></w:body></w:document>'};
test('DOCX uses bounded text and paragraph locations, rejects macros and unsafe ZIP metadata',async()=>{const bytes=zip(docEntries);const parsed=await parseDocument(bytes,docMime);assert.match(parsed.blocks[0].text,/Orbit Office 内容/);assert.match(parsed.blocks[0].location,/段落/);assert.throws(()=>validateOfficeArchive(zip({...docEntries,'word/vbaProject.bin':'macro'}),docMime),/宏/);assert.throws(()=>validateOfficeArchive(zip({...docEntries,'../file':'unsafe'}),docMime),/不安全/);const bomb=Buffer.from(bytes),central=bomb.indexOf(Buffer.from([80,75,1,2]));bomb.writeUInt32LE(50000000,central+24);assert.throws(()=>validateOfficeArchive(bomb,docMime),/超限/);await assert.rejects(parseDocument(zip({...docEntries,'[Content_Types].xml':docEntries['[Content_Types].xml']+'macroEnabled'}),docMime),/宏/);
  const manyParagraphs=docEntries['word/document.xml'].replace('</w:body>','<w:p><w:r><w:t>短段落</w:t></w:r></w:p>'.repeat(2001)+'</w:body>');const bounded=await parseDocument(zip({...docEntries,'word/document.xml':manyParagraphs}),docMime);assert.equal(bounded.blocks.length,2000);assert.equal(bounded.truncated,true);
});
test('XLSX preserves sheet/row locations and never computes formulas',async()=>{const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('安排');sheet.addRow(['事项','时间']);sheet.addRow(['开会','10:00']);sheet.getCell('C2').value={formula:'HYPERLINK("http://127.0.0.1/")',result:'仅缓存结果'};sheet.getCell('D2').value={formula:'1+1'};const bytes=Buffer.from(await book.xlsx.writeBuffer());const parsed=await parseDocument(bytes,sheetMime);assert.match(parsed.blocks[1].location,/安排.*第 2 行/);assert.match(parsed.blocks[1].text,/开会.*10:00.*仅缓存结果.*未执行/);});
test('CSV handles quoted commas/newlines and bounds rows without executing formulas',async()=>{const parsed=await parseDocument(Buffer.from('name,value\r\n"a,b","line1\nline2"\r\n=1+1,2'),'text/csv');assert.equal(parsed.blocks.length,3);assert.match(parsed.blocks[1].text,/a,b.*line1\nline2/);assert.match(parsed.blocks[2].text,/=1\+1/);await assert.rejects(parseDocument(Buffer.from('a,"unclosed'),'text/csv'),/引号/);const bounded=await parseDocument(Buffer.from('row\n'.repeat(1002)),'text/csv');assert.equal(bounded.blocks.length,1000);assert.equal(bounded.truncated,true);});
