import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import { randomBytes } from 'node:crypto';

process.env.DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'orbit-note-images-'));
process.env.APP_ENV = 'development'; process.env.NODE_ENV = 'test'; process.env.BACKGROUND_JOBS_ENABLED = 'false';
const api = await import('./index.js'), db = await import('./db.js'), notes = await import('./note-item-service.js'), images = await import('./note-image-service.js'), backups = await import('./backup-service.js');
await api.initializeServer();
const stamp = new Date().toISOString();
const users = ['image-one', 'image-two'].map(id => db.createUser({ id, email: id + '@example.invalid', password_hash: 'synthetic', role: 'user', disabled: 0, created_at: stamp, updated_at: stamp }));
test('图文图片完整生命周期、账号归属、冲突、合并、旧备份与缺图恢复', async () => {
  const [user, other] = users;
  const server = api.app.listen(0, '127.0.0.1'); await new Promise<void>(resolve => server.once('listening', resolve));
  const base = `http://127.0.0.1:${(server.address() as { port: number }).port}`;
  const request = (pathname: string, owner = user, init: RequestInit = {}) => fetch(base + pathname, { ...init, headers: { Authorization: 'Bearer ' + api.signUserToken(owner), 'Content-Type': 'application/json', ...init.headers } });
  try {
    const uploaded: import('../src/utils/note-images.js').NoteImage[] = [];
    for (const color of ['#cc3355', '#338855', '#3366aa', '#bb8833']) {
      const bytes = await sharp({ create: { width: 48, height: 32, channels: 3, background: color } }).png().toBuffer();
      const response = await request('/api/note-items/images', user, { method: 'POST', body: JSON.stringify({ name: 'image.png', mime: 'image/png', base64: bytes.toString('base64') }) });
      assert.equal(response.status, 201); uploaded.push((await response.json()).image);
    }
    assert.equal((await request('/api/note-items/images/' + uploaded[0].id, other)).status, 404);
    assert.equal((await request('/api/note-items/images/' + uploaded[0].id, other, { method: 'DELETE' })).status, 404);
    const invalid = await request('/api/note-items/images', user, { method: 'POST', body: JSON.stringify({ name: 'fake.png', mime: 'image/png', base64: Buffer.from('not an image').toString('base64') }) }); assert.equal(invalid.status, 400);
    const large = await sharp(randomBytes(1024 * 512 * 3), { raw: { width: 1024, height: 512, channels: 3 } }).png({ compressionLevel: 0 }).toBuffer();
    assert.ok(large.length > 1024 * 1024);
    const largeResponse = await request('/api/note-items/images', user, { method: 'POST', body: JSON.stringify({ name: 'large.png', mime: 'image/png', base64: large.toString('base64') }) });
    assert.equal(largeResponse.status, 201); const largeImage = (await largeResponse.json()).image;
    assert.equal((await request('/api/note-items/images/' + largeImage.id, user, { method: 'DELETE' })).status, 200);
    const oversized = await request('/api/note-items/images', user, { method: 'POST', body: JSON.stringify({ name: 'oversized.png', mime: 'image/png', base64: Buffer.alloc(10 * 1024 * 1024 + 1).toString('base64') }) }); assert.equal(oversized.status, 400);
    assert.throws(() => notes.createNoteItems(other.id, 'foreign', 'neutral', [uploaded[0].id]), /无权/);
    assert.throws(() => notes.createNoteItems(user.id, 'duplicate', 'neutral', [uploaded[0].id, uploaded[0].id]), /不同/);
    const [card] = notes.createNoteItems(user.id, '第一段\n\n第二段', 'neutral', [uploaded[0].id, uploaded[1].id]);
    assert.equal(card.content, '第一段\n\n第二段'); assert.equal(card.images.length, 2);
    const [imageOnly] = notes.createNoteItems(user.id, '', 'neutral', [uploaded[2].id]); assert.equal(imageOnly.content, '');
    const [tooMany] = notes.createNoteItems(user.id, 'fourth', 'neutral', [uploaded[3].id]);
    const edited = notes.updateNoteItem(user.id, card.id, { content: card.content, imageIds: [uploaded[1].id, uploaded[0].id], expectedRevision: 0 })!;
    assert.throws(() => notes.updateNoteItem(user.id, card.id, { imageIds: [], expectedRevision: 0 }), notes.NoteContentConflict);
    const optimized = notes.commitOptimizedNote(user.id, card.id, edited.content, edited.contentRevision, '优化文字')!; assert.deepEqual(optimized.images, edited.images);
    const merged = notes.mergeNoteItems(user.id, imageOnly.id, card.id)!;
    assert.throws(() => notes.mergeNoteItems(user.id, tooMany.id, card.id), /3/);
    assert.equal(notes.getNoteItem(user.id, tooMany.id)?.completed, false);
    assert.equal(notes.getNoteItem(user.id, card.id)?.images.length, 3);
    assert.deepEqual(merged.target.images.map(image => image.id), [uploaded[1].id, uploaded[0].id, uploaded[2].id]); assert.equal(merged.source.images.length, 1);
    assert.equal((await request('/api/note-items/images/' + uploaded[2].id, user, { method: 'DELETE' })).status, 400);
    notes.deleteNoteItem(user.id, imageOnly.id); assert.ok(images.readNoteImage(user.id, uploaded[2].id).bytes.length);
    const [backupImageOnly] = notes.createNoteItems(user.id, '', 'neutral', [uploaded[3].id]);
    const draftImage = await images.uploadNoteImage(user.id, { name: 'unbound-draft.png', mime: 'image/png', base64: images.readNoteImage(user.id, uploaded[0].id).bytes.toString('base64') });
    const password = 'synthetic-backup-password';
    const backup = backups.createUserBackup(user.id, password);
    const restored = backups.restoreUserBackup(other.id, backup, password, 'replace'); assert.equal(restored.status, 'COMPLETED');
    const restoredCard = notes.listNoteItems(other.id).find(note => note.images.length === 3)!; assert.ok(restoredCard); assert.notEqual(restoredCard.id, card.id); assert.notEqual(restoredCard.images[0].id, uploaded[1].id);
    assert.ok(notes.listNoteItems(other.id).some(note => !note.content && note.images.length === 1));
    const activity = await import('./activity-store.js'), connection = await import('./database/connection.js');
    const restoredDraft = activity.listAttachments(other.id).find(file => file.originalName === 'unbound-draft.png')!;
    assert.ok(images.readNoteImage(other.id, restoredDraft.id).bytes.length);
    connection.run('UPDATE note_images SET created_at=? WHERE user_id=?', [new Date(Date.now() - 86400001).toISOString(), other.id]);
    images.cleanupNoteImageDrafts(other.id); assert.throws(() => images.readNoteImage(other.id, restoredDraft.id), /不存在/); assert.ok(images.readNoteImage(other.id, restoredCard.images[0].id).bytes.length);
    const legacy = backups.decryptBackup<any>(backup, password); delete legacy.noteImages;
    assert.throws(() => backups.restoreUserBackup(other.id, backups.encryptBackup(legacy, password), password, 'replace'), /合并/);
    const before = notes.listNoteItems(user.id);
    backups.restoreUserBackup(user.id, backups.encryptBackup(legacy, password), password, 'merge'); assert.deepEqual(notes.listNoteItems(user.id), before);
    const missing = backups.decryptBackup<any>(backup, password); missing.files = missing.files.filter((file: any) => file.attachmentId !== uploaded[1].id);
    const partial = backups.restoreUserBackup(other.id, backups.encryptBackup(missing, password), password, 'replace'); assert.equal(partial.status, 'PARTIAL'); assert.deepEqual(partial.missingNoteImages, [uploaded[1].id]);
    const orbit = await import('./orbit-store.js'), attachments = await import('./orbit-attachments.js');
    const conversation = orbit.ensureDefaultConversation(user.id);
    const chatImage = await attachments.uploadChatAttachment(user.id, conversation, { name: 'shared.png', mime: 'image/png', base64: images.readNoteImage(user.id, uploaded[0].id).bytes.toString('base64') });
    attachments.clearConversationAttachments(user.id, conversation);
    assert.throws(() => attachments.attachment(user.id, chatImage.id), /不存在/); assert.ok(images.readNoteImage(user.id, uploaded[0].id).bytes.length);
    notes.deleteNoteItem(user.id, card.id); assert.throws(() => images.readNoteImage(user.id, uploaded[0].id), /不存在/);
    notes.deleteNoteItem(user.id, backupImageOnly.id); notes.deleteNoteItem(user.id, tooMany.id); assert.throws(() => images.readNoteImage(user.id, uploaded[3].id), /不存在/);
    images.deleteUnboundNoteImage(user.id, draftImage.id);
  } finally { server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); }
});
