import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import sharp from 'sharp';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'orbit-files-test-'));Object.assign(process.env,{DATA_DIR:root,NODE_ENV:'test',APP_ENV:'development',BACKGROUND_JOBS_ENABLED:'false',ORBIT_PROACTIVE_ENABLED:'false'});
const api=await import('./index.js');await api.initializeServer();const db=await import('./db.js'),store=await import('./orbit-store.js'),files=await import('./orbit-attachments.js'),{parseDocument}=await import('./file-parser.js'),{run}=await import('./database/connection.js');
const stamp=new Date().toISOString();for(const id of ['files-owner','files-other'])db.createUser({id,email:id+'@example.invalid',password_hash:'synthetic',role:'user',disabled:0,created_at:stamp,updated_at:stamp});const cid=store.ensureDefaultConversation('files-owner');
const upload=(text='Orbit file content',mime='text/plain',name='notes.txt')=>files.uploadChatAttachment('files-owner',cid,{name,mime,base64:Buffer.from(text).toString('base64')});
test('owned attachment metadata and message references survive restore; other accounts cannot read',async()=>{const file=await upload();assert.equal(file.state,'ready');assert.throws(()=>files.attachment('files-other',file.id),/不存在/);const message=randomUUID();db.createAiScheduleMessage({id:message,user_id:'files-owner',conversation_id:cid,role:'user',type:'text',content:'资料',intent:null,schedule_items:null,plan:null,created_at:stamp});files.linkMessageAttachments('files-owner',message,[file.id]);assert.equal(files.messageAttachments('files-owner',message)[0].name,'notes.txt');assert.deepEqual(files.selectAttachmentIds('files-owner',cid,'这份文件说什么',[]),[file.id]);const backup=store.exportOrbit('files-owner');store.restoreOrbit('files-owner',backup,'replace');assert.equal(files.messageAttachments('files-owner',message)[0].id,file.id);const context=files.attachmentContext('files-owner',[file.id],'概述');assert.match(context.input[0].text!,/Orbit file content/);});
test('limits, MIME forgery, busy deletion and 24 hour cleanup are enforced',async()=>{await assert.rejects(upload('\0binary'),/二进制/);await assert.rejects(upload('fake pdf','application/pdf','fake.pdf'),/类型不一致/);const file=await upload('busy');assert.throws(()=>files.validateChatAttachments('files-owner',store.createConversation('files-owner','other').id,[file.id]),/当前会话/);assert.throws(()=>files.validateChatAttachments('files-owner',cid,[file.id,file.id]),/不同附件/);const request=randomUUID();run('INSERT INTO orbit_requests(id,user_id,conversation_id,state,body,created_at) VALUES (?,?,?,?,?,?)',[request,'files-owner',cid,'queued',JSON.stringify({attachmentIds:[file.id]}),stamp]);assert.throws(()=>files.deleteChatAttachment('files-owner',file.id),/正在使用/);run('DELETE FROM orbit_requests WHERE id=?',[request]);run('UPDATE orbit_attachments SET created_at=? WHERE id=?',[new Date(Date.now()-90000000).toISOString(),file.id]);files.cleanupUnsentAttachments('files-owner');assert.throws(()=>files.attachment('files-owner',file.id),/不存在/);});
test('native images are decoded, resized and included as actual multimodal input',async()=>{const bytes=await sharp({create:{width:2600,height:12,channels:3,background:'white'}}).png().toBuffer();const image=await files.uploadChatAttachment('files-owner',cid,{name:'image.png',mime:'image/png',base64:bytes.toString('base64')});const input=files.attachmentContext('files-owner',[image.id],'查看图片');assert.equal(input.images,true);const metadata=await sharp(Buffer.from(input.input[0].data!,'base64')).metadata();assert.equal(metadata.width,2048);assert.equal(metadata.exif,undefined);});
function pdf(text:string){const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 300] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${('BT /F1 12 Tf 30 200 Td ('+text+') Tj ET').length} >>\nstream\nBT /F1 12 Tf 30 200 Td (${text}) Tj ET\nendstream`];let data='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(data.length);data+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const offset=data.length;data+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${offset}\n%%EOF`;return Buffer.from(data);}
test('PDF extraction keeps page location, broken input and cancellation fail explicitly',async()=>{const parsed=await parseDocument(pdf('OrbitDocument'),'application/pdf');assert.equal(parsed.blocks[0].location,'第 1 页');assert.match(parsed.blocks[0].text,/OrbitDocument/);await assert.rejects(parseDocument(Buffer.from('%PDF-broken'),'application/pdf'));const controller=new AbortController();const pending=parseDocument(Buffer.alloc(10000000,65),'text/plain',controller.signal);controller.abort();await assert.rejects(pending,/取消/);});
test('document context has a bounded conservative token budget and reports excerpts',async()=>{const file=await upload('信息'.repeat(10000));const result=files.attachmentContext('files-owner',[file.id],'信息');assert.match(result.notice,/节选/);assert.ok(Buffer.byteLength(result.input[0].text!)<12500);});
test('encrypted user backup restores shared files and conversation/message references in another account',async()=>{const backup=await import('./backup-service.js');const bytes=backup.createUserBackup('files-owner','synthetic-password-123');const result=backup.restoreUserBackup('files-other',bytes,'synthetic-password-123','replace');assert.equal(result.status,'COMPLETED');const restored=store.exportOrbit('files-other');assert.ok(restored.attachments.length>0);assert.ok(restored.attachmentLinks.length>0);for(const link of restored.attachmentLinks){assert.equal(files.messageAttachments('files-other',link.message_id)[0].conversationId,restored.conversations.find(c=>c.id===files.attachment('files-other',link.attachment_id).conversation_id)?.id);assert.throws(()=>files.attachment('files-owner',link.attachment_id),/不存在/);}});

test('HTTP uploads exceed the old JSON body limit, remain owned and authenticated SSE ends at terminal state',async()=>{
  const server=api.app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
  const request=(uid:string,url:string,init:RequestInit={})=>fetch(base+url,{...init,headers:{Authorization:'Bearer '+api.signUserToken(db.getUserById(uid)!),'Content-Type':'application/json',...init.headers}});
  try{
    const response=await request('files-owner',`/api/orbit/conversations/${cid}/attachments`,{method:'POST',body:JSON.stringify({name:'large.txt',mime:'text/plain',base64:Buffer.alloc(1100000,65).toString('base64')})});assert.equal(response.status,200);const file=(await response.json()).attachment;assert.equal(file.state,'ready');
    assert.equal((await fetch(base+`/api/orbit/attachments/${file.id}`)).status,401);
    assert.equal((await request('files-other',`/api/orbit/attachments/${file.id}`)).status,400);
    const download=await request('files-owner',`/api/orbit/attachments/${file.id}`);assert.equal((await download.arrayBuffer()).byteLength,1100000);assert.match(download.headers.get('content-disposition')!,/attachment/);
    const id=randomUUID();run('INSERT INTO orbit_requests(id,user_id,conversation_id,state,body,created_at) VALUES (?,?,?,?,?,?)',[id,'files-owner',cid,'completed',JSON.stringify({text:'合成状态'}),stamp]);
    assert.equal((await request('files-other',`/api/orbit/requests/${id}/events`)).status,404);
    const events=await request('files-owner',`/api/orbit/requests/${id}/events`);assert.match(events.headers.get('content-type')!,/text\/event-stream/);assert.match(await events.text(),/completed/);
  }finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}
});

test('missing backup files do not restore ghost message links and account cleanup removes provider data',async()=>{
  const backup=store.exportOrbit('files-owner');backup.attachments.push({id:'missing-file',conversation_id:cid,state:'ready',created_at:stamp} as any);backup.attachmentLinks.push({message_id:backup.messages[0].id,attachment_id:'missing-file'} as any);store.restoreOrbit('files-owner',backup,'merge');assert.ok(!store.exportOrbit('files-owner').attachments.some(a=>a.id==='missing-file'));
  const vault=await import('./orbit-credential-vault.js');vault.saveSecret('chatgpt','files-other',{synthetic:true});run('INSERT INTO orbit_model_capabilities(user_id,provider,model,credential_version,capability,verified_at) VALUES (?,?,?,?,?,?)',['files-other','workbuddy','synthetic','v1','images',stamp]);db.clearUserData('files-other');
  assert.equal(store.exportOrbit('files-other').attachments.length,0);assert.equal(vault.loadSecret('chatgpt','files-other'),undefined);
  const {queryAll}=await import('./database/connection.js');assert.equal(queryAll('SELECT * FROM orbit_model_capabilities WHERE user_id=?',['files-other']).length,0);
});
