import {useEffect,useRef,useState} from 'react';
import {Paperclip,X,FileText} from 'lucide-react';
import type {ChatFile} from '../hooks/useChatAttachments';
export function ChatAttachmentCard({file,authHeaders}:{file:ChatFile;authHeaders:()=>Record<string,string>}) {
  const [thumbnail,setThumbnail]=useState(''),[error,setError]=useState('');
  useEffect(()=>{if(!file.mime.startsWith('image/'))return;const controller=new AbortController();let url='';void fetch(`/api/orbit/attachments/${encodeURIComponent(file.id)}`,{headers:authHeaders(),signal:controller.signal}).then(async res=>{if(!res.ok)return;url=URL.createObjectURL(await res.blob());if(!controller.signal.aborted)setThumbnail(url);else URL.revokeObjectURL(url);}).catch(()=>{});return()=>{controller.abort();if(url)URL.revokeObjectURL(url);};},[file.id,file.mime,authHeaders]);
  const download=async()=>{try{setError('');const res=await fetch(`/api/orbit/attachments/${encodeURIComponent(file.id)}`,{headers:authHeaders()});if(!res.ok)throw new Error('附件已删除或无法读取');const url=URL.createObjectURL(await res.blob()),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'下载失败');}};
  return <div className="orbit-file-card">{thumbnail?<img src={thumbnail} alt={file.name}/>:<FileText size={20} aria-hidden="true"/>}<div><strong>{file.name}</strong><small>{(file.size/1024).toFixed(1)} KB · 已关联此对话</small></div><button type="button" onClick={()=>void download()} aria-label={`下载附件 ${file.name}`}>下载</button>{error&&<p role="alert">{error}</p>}</div>;
}
export function ChatAttachmentComposer({files,error,upload,remove,retry,disabled}:{files:ChatFile[];error:string;upload:(files:File[])=>Promise<void>;remove:(id:string)=>Promise<void>;retry:(id:string)=>Promise<void>;disabled?:boolean}){const input=useRef<HTMLInputElement>(null);return <div className="orbit-attachments-composer"><input ref={input} type="file" hidden multiple accept=".jpg,.jpeg,.png,.webp,.txt,.md,.pdf,.docx,.xlsx,.csv" onChange={e=>{const selected=Array.from(e.target.files||[]);e.target.value='';void upload(selected);}}/><button type="button" disabled={disabled||files.length>=3} onClick={()=>input.current?.click()} aria-label="添加图片或文件"><Paperclip size={15}/>附件</button>{files.map(file=><div className="orbit-draft-file" key={file.id}><span>{file.name}</span><small>{file.state==='uploading'?`上传 ${file.progress||0}%`:file.state==='processing'?'解析中':file.state==='ready'?'已就绪':file.error||'上传失败'}</small>{file.state==='failed'&&<button type="button" onClick={()=>void retry(file.id)}>重试解析</button>}<button type="button" aria-label={`移除附件 ${file.name}`} onClick={()=>void remove(file.id)}><X size={14}/></button></div>)}{error&&<p role="alert">{error}</p>}</div>;}
