import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { safeOrbitLink } from '../utils/orbit-links';
import '../styles/orbit-statistics.css';
interface Detail {id:string;title:string;date:string;href:string|null}
interface Statistics {
  filters?:{taskType:string;reportSource:string};window:{start:string;end:string;startAt:string;endAt:string;timezone:string;asOf:string};trackingSince:string;historyTracked:boolean;
  tasks:{total:number;completed:number;pending:number;rate:number|null;unknownCompletedAt:number};reports:{total:number;candidates:number};
  knowledge:{active:number;added:number;reads:number;citations:number};details:Array<Detail&{completed:boolean}>;knowledgeDetails:Detail[];reportDetails:Array<{id:string;reportDate:string;source:string}>;
  activity:{created:number;actualCompleted:number;backlog:number;overdue:number;aging:number;averageCompletionHours:number|null;completionSamples:number;rescheduled:number|null;notesAdded:number;notesOptimized:number|null;aiConfirmed:number|null;reminderCompleted:number;toolUses:number;heatmap:number[][];sources?:Array<{id:string;count:number}>;categories:Array<{id:string;count:number}>;daily:Array<{date:string;created:number;completed:number;notes:number;rescheduled:number}>;coverage:{since:string;mode:string};metricDetails:Record<string,Detail[]>;upcoming:Detail[]};
}
interface Report {id:string;rangeStart:string;rangeEnd:string;snapshotHash:string;snapshot:Statistics;insights:Array<{text:string;metrics:string[];objects:string[]}>;insightError:string|null;deliveries?:Array<{id:string;channel:string;status:string;lastError:string|null}>}
const names:Record<string,string>={created:'新增事项',completed:'实际完成',backlog:'当前无日期待办',overdue:'逾期事项',aging:'长期未处理',rescheduled:'改期操作',notes:'新增记事',optimized:'成功优化',ai:'AI 确认执行',tools:'有效工具协助',assisted:'提醒卡片完成',reads:'知识阅读',citations:'实际引用',knowledge:'新增知识',intervals:'创建至完成间隔'};
function Objects({rows,emptyText="没有符合此口径的记录。"}:{rows:Detail[];emptyText?:string}) {const [limit,setLimit]=useState(20);useEffect(()=>setLimit(20),[rows]);return <>{rows.length?<ul className="activity-objects">{rows.slice(0,limit).map((d,i)=>{const href=d.href&&safeOrbitLink(d.href,window.location.origin);return <li key={`${d.id}:${i}`}>{href?<Link to={href}>{d.title}</Link>:<span>{d.title} · 对象已移除或无法定位</span>}<time>{d.date?.replace('T',' ').slice(0,19)}</time></li>;})}</ul>:<p className="orbit-stat-muted">{emptyText}</p>}{rows.length>limit&&<button onClick={()=>setLimit(v=>v+20)}>再显示 20 条（共 {rows.length} 条）</button>}</>;}
export function UsageStatisticsView() {
  const {authHeaders}=useAuth();const [params,setParams]=useSearchParams();const reportId=params.get('report');
  const [period,setPeriod]=useState('week'),[date,setDate]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[taskType,setTaskType]=useState('all'),[reportSource,setReportSource]=useState('all');
  const [data,setData]=useState<Statistics|null>(null),[report,setReport]=useState<Report|null>(null),[saved,setSaved]=useState<Array<{id:string;rangeStart:string;rangeEnd:string}>>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[retry,setRetry]=useState(0),[confirmSend,setConfirmSend]=useState(false),[changed,setChanged]=useState(false);
  const request=async(path:string,method='GET',body?:unknown)=>{const r=await fetch(path,{method,headers:{...authHeaders(),...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'操作失败');return d;};
  const query=new URLSearchParams({period,taskType,reportSource,...(date?{date}:{}),...(period==='custom'&&from&&to?{from:new Date(from).toISOString(),to:new Date(to).toISOString()}:{})}).toString();
  useEffect(()=>{const c=new AbortController();setError('');setChanged(false);setData(null);setReport(null);setConfirmSend(false);if(!reportId&&period==='custom'&&(!from||!to)){setError('请选择开始与结束时间；结束时刻不包含在范围内。');return;}void fetch(reportId?`/api/orbit/activity-reports/${encodeURIComponent(reportId)}`:`/api/orbit/statistics?${query}`,{headers:authHeaders(),signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'报告加载失败');if(reportId){setReport(d);setData(d.snapshot);}else setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[reportId,query,retry,authHeaders]);
  useEffect(()=>{const c=new AbortController();void fetch('/api/orbit/activity-reports',{headers:authHeaders(),signal:c.signal}).then(r=>r.json()).then(d=>setSaved(d.reports||[])).catch(()=>undefined);return()=>c.abort();},[retry,reportId,authHeaders]);
  useEffect(()=>{const change=()=>{if(report)setChanged(true);else setRetry(v=>v+1);};const check=()=>{if(report)void request('/api/orbit/activity-reports/'+report.id+'/current').then(d=>setChanged(d.changed)).catch(()=>undefined);};check();window.addEventListener('focus',check);window.addEventListener('orbit:data-change',change);return()=>{window.removeEventListener('orbit:data-change',change);window.removeEventListener('focus',check);};},[report,authHeaders]);
  const reset=()=>{const next=new URLSearchParams(params);next.delete('report');setParams(next);setRetry(v=>v+1);};
  const shift=(n:number)=>{if(!data||period==='custom')return;const d=new Date(`${data.window.start}T12:00:00Z`);if(period==='week')d.setUTCDate(d.getUTCDate()+7*n);else if(period==='month')d.setUTCMonth(d.getUTCMonth()+n);else d.setUTCFullYear(d.getUTCFullYear()+n);setDate(d.toISOString().slice(0,10));reset();};
  const action=async(kind:'save'|'insights'|'deliver')=>{if(!data)return;setBusy(kind);setError('');try{let current=report;if(!current||(changed&&kind!=='deliver')){current=await request('/api/orbit/activity-reports','POST',{period:'custom',from:data.window.startAt,to:data.window.endAt,taskType:data.filters?.taskType||taskType,reportSource:data.filters?.reportSource||reportSource});setChanged(false);}if(!current)throw new Error('报告生成失败');const currentId=current.id;if(kind==='insights')current=await request(`/api/orbit/activity-reports/${currentId}/insights`,'POST');if(kind==='deliver'){await request(`/api/orbit/activity-reports/${currentId}/deliver`,'POST',{confirm:true});current=await request(`/api/orbit/activity-reports/${currentId}`);setConfirmSend(false);}setReport(current);setData(current!.snapshot);const next=new URLSearchParams(params);next.set('report',current!.id);setParams(next);setRetry(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy('');}};
  const prepareSend=async()=>{if(!data)return;setBusy('save');setError('');try{const current=report&&!changed?report:await request('/api/orbit/activity-reports','POST',{period:'custom',from:data.window.startAt,to:data.window.endAt,taskType:data.filters?.taskType||taskType,reportSource:data.filters?.reportSource||reportSource});setReport(current);setData(current.snapshot);setChanged(false);setConfirmSend(true);}catch(e){setError(e instanceof Error?e.message:'报告预览失败');}finally{setBusy('');}};
  const a=data?.activity;const metric=(key:string,value:number|string|null,label=names[key])=><div className="orbit-stat-metric" key={key}><span>{label}</span><strong>{value===null?'未记录':value}</strong>{a?.metricDetails[key]&&<details><summary>查看明细 · {a.metricDetails[key].length}</summary><Objects rows={a.metricDetails[key]}/></details>}</div>;
  const daily=data?Array.from({length:Math.round((Date.parse(data.window.end+'T12:00Z')-Date.parse(data.window.start+'T12:00Z'))/86400000)+1},(_,i)=>{const d=new Date(data.window.start+'T12:00Z');d.setUTCDate(d.getUTCDate()+i);const date=d.toISOString().slice(0,10);return a!.daily.find(v=>v.date===date)||{date,created:0,completed:0,notes:0,rescheduled:0};}):[];
  const maximum=Math.max(1,...daily.flatMap(d=>[d.created,d.completed]));const points=(field:'created'|'completed')=>daily.map((d,i)=>`${30+i*900/Math.max(1,daily.length-1)},${170-d[field]*140/maximum}`).join(' ');const heatMax=Math.max(1,...(a?.heatmap.flat()||[]));
  return <div className="orbit-statistics"><header><div><Link to="/assistant">← 返回 Orbit</Link><p className="activity-kicker">ORBIT · PERSONAL REPORT</p><h1>个人活动报告</h1><p className="orbit-stat-muted">执行、知识积累与 AI 协作</p></div><nav><Link to="/project?view=growth">项目成长</Link><Link to="/project?view=architecture">架构</Link><button onClick={()=>window.dispatchEvent(new CustomEvent('orbit:open-settings',{detail:'notifications'}))}>周报设置</button></nav></header>
    <div className="orbit-stat-controls"><div role="group" aria-label="报告周期">{[['week','周'],['month','月'],['year','年'],['custom','自定义']].map(([id,label])=><button key={id} aria-pressed={period===id&&!reportId} onClick={()=>{setPeriod(id);reset();}}>{label}</button>)}</div>{period==='custom'?<><label>开始（设备时区）<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>结束，不包含<input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label></>:<><label>选择日期<input type="date" value={date} onChange={e=>{setDate(e.target.value);reset();}}/></label><button disabled={!data||!!busy} onClick={()=>shift(-1)}>上一周期</button><button disabled={!data||!!busy} onClick={()=>shift(1)}>下一周期</button></>}
    <label>事项<select value={taskType} onChange={e=>{setTaskType(e.target.value);reset();}}><option value="all">全部</option><option value="event">日程</option><option value="todo">待办</option><option value="reminder">周期事项</option></select></label><label>日报来源<select value={reportSource} onChange={e=>{setReportSource(e.target.value);reset();}}><option value="all">全部</option><option value="local">Local</option><option value="cloud">Cloud</option></select></label><button onClick={()=>{setDate('');setPeriod('week');reset();}}>当前周期</button><label>已保存报告<select aria-label="已保存报告" value={reportId||''} onChange={e=>{const next=new URLSearchParams(params);if(e.target.value)next.set('report',e.target.value);else next.delete('report');setParams(next);}}><option value="">实时报告</option>{saved.map(r=><option key={r.id} value={r.id}>{new Date(r.rangeStart).toLocaleDateString('sv-SE',{timeZone:data?.window.timezone||'UTC'})} — {new Date(Date.parse(r.rangeEnd)-1).toLocaleDateString('sv-SE',{timeZone:data?.window.timezone||'UTC'})} · {data?.window.timezone||'UTC'}</option>)}</select></label></div>
    {error&&<p role="alert" className="activity-error">{error} <button onClick={()=>setRetry(v=>v+1)}>重试读取</button></p>}{!data&&!error&&<p role="status">正在读取个人活动…</p>}
    {data&&a&&<><p className="orbit-stat-muted">{data.window.start} 至 {data.window.end} · {data.window.timezone}{report&&' · 已保存快照'}<br/>精确范围：{data.window.startAt} ≤ 活动时间 &lt; {data.window.endAt}</p><section className="activity-overview"><div className="activity-ring" style={{background:`conic-gradient(var(--td-brand-color) ${(data.tasks.rate||0)*3.6}deg,var(--td-bg-color-secondarycontainer) 0)`}}><span>{data.tasks.rate===null?'—':data.tasks.rate+'%'}<small>安排完成率</small></span></div><div><h2>{a.actualCompleted?`本期实际完成 ${a.actualCompleted} 项`:'本期尚无有效完成记录'}</h2><p>新增 {a.created} 项事项，积累 {data.knowledge.added} 条知识。当前有 {a.overdue} 项逾期。</p><p className="orbit-stat-muted">周期事项与日历投影只计一次；无日期待办纳入新增、有效完成和积压。</p></div></section><div className="orbit-stat-grid activity-overview-metrics">{metric('completed',a.actualCompleted)}{metric('created',a.created)}{metric('backlog',a.backlog)}{metric('knowledge',data.knowledge.added)}</div>
    <section><h2>执行趋势</h2><p className="orbit-stat-muted">每日新增与有效完成 · <span className="activity-legend-created">● 新增</span> · <span className="activity-legend-completed">● 完成</span></p><svg className="activity-trend" viewBox="0 0 960 210" role="img" aria-label="每日新增与实际完成趋势，精确数据见下方数据表"><line x1="30" y1="170" x2="930" y2="170" stroke="currentColor" opacity=".25"/><text x="5" y="35">{maximum}</text><text x="10" y="172">0</text><polyline points={points('created')} fill="none" stroke="var(--td-brand-color)" strokeWidth="3"/><polyline points={points('completed')} fill="none" stroke="var(--td-success-color, #2d8b65)" strokeWidth="3"/><text x="30" y="203">{data.window.start}</text><text x="930" y="203" textAnchor="end">{data.window.end}</text></svg><details><summary>展开数据表</summary><div className="orbit-stat-table"><table><thead><tr><th>日期</th><th>新增</th><th>实际完成</th><th>记事</th><th>改期</th></tr></thead><tbody>{daily.map(d=><tr key={d.date}><th>{d.date}</th><td>{d.created}</td><td>{d.completed}</td><td>{d.notes}</td><td>{d.date<a.coverage.since.slice(0,10)?'未记录':d.rescheduled}</td></tr>)}</tbody></table></div></details></section>
    <div className="activity-columns"><section><h2>节律</h2><p className="orbit-stat-muted">事项创建、有效完成、用户聊天与记事创建；系统通知不计入。</p><div className="activity-heatmap" role="group" aria-label="星期与小时活动热图"><div className="activity-heat-labels"><span/>{[0,6,12,18].map(h=><span key={h}>{h}:00</span>)}</div>{a.heatmap.map((row,i)=><div className="activity-heat-row" key={i}><span>{['一','二','三','四','五','六','日'][i]}</span>{row.map((value,h)=><button key={h} title={`周${['一','二','三','四','五','六','日'][i]} ${h}:00：${value} 次活动`} aria-label={`周${['一','二','三','四','五','六','日'][i]} ${h} 点：${value} 次活动`} style={{background:value?`color-mix(in srgb,var(--td-brand-color) ${20+value/heatMax*70}%,var(--td-bg-color-container))`:undefined}}/>)}</div>)}</div><p className="orbit-stat-muted">浅 → 深表示活动次数，不表示专注时长。</p></section><section><h2>完成度</h2><strong className="activity-large">{data.tasks.rate===null?'暂无安排':data.tasks.rate+'%'}</strong><p>本期安排完成 {data.tasks.completed} / {data.tasks.total} 项</p><div className="activity-progress"><span style={{width:`${data.tasks.rate||0}%`}}/></div><p className="orbit-stat-muted">分母是本期安排日期内事项及周期实例，分子是其中当前已完成事项。实际完成按有效完成时间统计，包含无日期待办。</p><details><summary>本期安排 · {data.tasks.pending} 项未完成</summary><Objects rows={data.details}/></details>{metric('intervals',a.averageCompletionHours===null?'暂无可靠样本':`${a.averageCompletionHours} 小时`)}<p className="orbit-stat-muted">创建至完成间隔，可靠样本 {a.completionSamples} 项。{data.tasks.unknownCompletedAt>0&&`${data.tasks.unknownCompletedAt} 项历史完成时间未记录。`}</p></section></div>
    <section><h2>积压与逾期</h2><p className="orbit-stat-muted">当前状态快照：{new Date(data.window.asOf).toLocaleString()}。长期未处理指创建超过七天的无日期待办；不反推历史积压。</p><div className="orbit-stat-grid">{metric('backlog',a.backlog)}{metric('overdue',a.overdue)}{metric('aging',a.aging)}{metric('rescheduled',a.rescheduled)}</div><p className="orbit-stat-muted">逾期是当前状态；改期只计有记录的日期变更操作。</p></section>
    <section><h2>知识积累</h2><div className="orbit-stat-grid">{metric('notes',a.notesAdded)}{metric('optimized',a.notesOptimized)}{metric('knowledge',data.knowledge.added)}{metric('reads',data.historyTracked?data.knowledge.reads:null)}{metric('citations',data.historyTracked?data.knowledge.citations:null)}</div><p className="orbit-stat-muted">知识当前有效 {data.knowledge.active} 条。阅读同条目半小时内去重；每条 AI 回复只计实际引用的条目。采集起点 {data.trackingSince.slice(0,10)}，历史未采集不表示零。</p><details><summary>知识条目</summary><Objects rows={data.knowledgeDetails}/></details></section>
    <section><h2>AI 协作与主题</h2><div className="orbit-stat-grid">{metric('ai',a.aiConfirmed)}{metric('assisted',a.reminderCompleted)}{metric('tools',a.toolUses)}</div><p className="orbit-stat-muted">确认执行的创建或修改、成功工具步骤、从提醒卡片完成。建议生成不计采纳；不推断 AI 导致完成。</p><div className="activity-categories">{a.categories.length?a.categories.map(c=><details key={c.id}><summary>{({life:'生活',work:'工作',study:'学习',other:'其他'} as Record<string,string>)[c.id]||c.id} · {c.count} 项</summary><Objects rows={a.metricDetails['category:'+c.id]||[]}/></details>):<p className="orbit-stat-muted">本期没有分类事项。</p>}</div><p className="orbit-stat-muted">分类表示本期新增事项数量，不表示精力或时间占比。</p><div className="activity-categories">{a.sources?.map(s=><details key={s.id}><summary>创建来源：{({manual:'手动',ai:'AI 确认',import:'导入',unknown:'未记录'} as Record<string,string>)[s.id]} · {s.count}</summary><Objects rows={a.metricDetails['source:'+s.id]||[]}/></details>)}</div></section>
    <section><h2>洞察与明细</h2><p className="orbit-stat-muted">改期、来源、AI 确认与记事优化从 {a.coverage.since.slice(0,10)} 开始采集。{a.coverage.mode==='complete'?'本期在采集范围内。':a.coverage.mode==='none'?'本期这些事件未记录。':'本期只覆盖部分采集时间，请勿按全期比较。'}</p>{changed&&<p role="status">数据已变化，当前展示已保存快照。可重新生成洞察更新快照。</p>}<div className="activity-report-actions"><button disabled={!!busy} onClick={()=>void action('save')}>{busy==='save'?'保存中…':'保存事实报告'}</button><button disabled={!!busy} onClick={()=>void action('insights')}>{busy==='insights'?'正在生成洞察…':report?.insights.length?'重新生成洞察':'生成洞察'}</button><button disabled={!!busy} onClick={()=>void prepareSend()}>预览并发送周报</button></div>{report?.insightError&&<p role="status">{report.insightError}。事实报告仍可阅读。</p>}{report?.insights.map((i,index)=><article className="activity-insight" key={index}><p>{i.text}</p><small>统计依据：{i.metrics.map(m=>names[m]||m).join('、')}</small><Objects emptyText="本条洞察基于汇总统计，未关联具体对象；可展开对应指标查看明细。" rows={Object.values(a.metricDetails).flat().filter(d=>i.objects.includes(d.id)).filter((d,n,rows)=>rows.findIndex(v=>v.id===d.id)===n)}/></article>)}{!report?.insights.length&&<p className="orbit-stat-muted">点击生成后使用当前账号的 Provider 与模型；模型只读取有界统计和事项摘要。</p>}
    {confirmSend&&<div className="activity-send-preview" role="region" aria-label="周报发送预览"><h3>Orbit Weekly · 发送预览</h3><p>{data.window.start} — {data.window.end} · 完成 {a.actualCompleted} 项，新增 {a.created} 项，积压 {a.backlog} 项，逾期 {a.overdue} 项。</p><p>知识新增 {data.knowledge.added} 条，记事新增 {a.notesAdded} 条，AI 确认执行 {a.aiConfirmed??'未记录'} 项。</p>{report?.insights.map((i,n)=><p key={n}>{i.text}</p>)}<h4>下一周期到期事项</h4><Objects rows={a.upcoming}/><p className="orbit-stat-muted">预览已绑定事实快照；确认后发送这份报告到已开启的邮件与站内渠道。同一报告和渠道去重；模型不可用时发送事实版。</p><button disabled={!!busy} onClick={()=>void action('deliver')}>{busy==='deliver'?'排队中…':'确认发送这份报告'}</button><button disabled={!!busy} onClick={()=>setConfirmSend(false)}>取消</button></div>}{report?.deliveries?.map(d=><p className="orbit-stat-muted" key={d.id}>{d.channel==='email'?'邮件':'站内'}：{({pending:'已排队',sending:'投递中',sent:d.channel==='email'?'SMTP accepted（收件箱未验证）':'已投递聊天',failed:'失败',suppressed:'已停止投递'} as Record<string,string>)[d.status]||d.status}{d.lastError&&` · ${d.lastError}`}</p>)}<details><summary>情报日报 · {data.reports.total} 份</summary><p className="orbit-stat-muted">与个人周报独立，同日同来源重发计一份；候选 {data.reports.candidates} 份不计入。</p><ul>{data.reportDetails.map(r=><li key={r.id}><Link to={'/reports/'+r.reportDate}>{r.reportDate} · {r.source}</Link></li>)}</ul></details></section></>}
  </div>;
}
