import { createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode } from 'react';
import { searchSettings,type SearchableSetting } from '../../utils/settings-search';
export const SettingSectionContext=createContext('');
const IndexContext=createContext<{register:(item:SearchableSetting,element:HTMLElement)=>()=>void}>({register:()=>()=>{}});
export const useSettingIndex=()=>useContext(IndexContext);
export function SettingsSearchProvider({children}:{children:ReactNode}) {
  const [entries,setEntries]=useState<Map<string,{item:SearchableSetting;element:HTMLElement}>>(new Map()),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[selected,setSelected]=useState(0);
  const register=useCallback((item:SearchableSetting,element:HTMLElement)=>{setEntries(old=>new Map(old).set(item.id,{item,element}));return()=>setEntries(old=>{const next=new Map(old);if(next.get(item.id)?.element===element)next.delete(item.id);return next;});},[]);
  const context=useMemo(()=>({register}),[register]);
  const results=useMemo(()=>searchSettings([...entries.values()].map(e=>e.item),query),[entries,query]);
  useEffect(()=>{const close=()=>setOpen(false);window.addEventListener('orbit:settings-search-close',close);return()=>window.removeEventListener('orbit:settings-search-close',close);},[]);
  const navigate=(item:SearchableSetting)=>{setOpen(false);const element=entries.get(item.id)?.element;if(!element)return;document.dispatchEvent(new CustomEvent('orbit:settings-section',{detail:item.section}));element.scrollIntoView({block:'center',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});const control=[...element.querySelectorAll<HTMLElement>('input:not(:disabled),select:not(:disabled),textarea:not(:disabled),button:not(:disabled),a[href]')].find(e=>e.getClientRects().length>0);(control||element).focus({preventScroll:true});element.classList.add('setting-search-target');setTimeout(()=>element.classList.remove('setting-search-target'),1800);};
  return <IndexContext.Provider value={context}><div className="settings-search" data-settings-search-open={open&&!!query}><label className="sr-only" htmlFor="orbit-settings-search">搜索设置</label><input id="orbit-settings-search" role="combobox" aria-autocomplete="list" aria-expanded={open&&!!query} aria-controls="orbit-settings-search-results" aria-activedescendant={open&&results[selected]?`setting-result-${results[selected].id}`:undefined} placeholder="搜索设置、名称或关键词" autoComplete="off" value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true);setSelected(0);}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setOpen(false);}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setOpen(true);setSelected(i=>Math.max(0,Math.min(results.length-1,i+(e.key==='ArrowDown'?1:-1))));}else if(e.key==='Enter'&&results[selected]){e.preventDefault();navigate(results[selected]);}}}/>{open&&query&&<div className="settings-search-results" id="orbit-settings-search-results" role="listbox" aria-label="设置搜索结果">{results.length?results.map((item,i)=><button key={item.id} id={`setting-result-${item.id}`} role="option" aria-selected={selected===i} type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>navigate(item)}><strong>{item.label}</strong><small>{item.description||item.section}</small></button>):<p role="status">没有匹配的设置项</p>}</div>}</div>{children}</IndexContext.Provider>;
}
